# Generated by Django 4.1.6 on 2023-02-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Сфера',
                'verbose_name_plural': 'Сферы',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('oname', models.CharField(max_length=200, verbose_name='Отчество')),
                ('position', models.TextField(verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт')),
                ('contact_tel', models.CharField(blank=True, max_length=200, verbose_name='Контакт телефон')),
                ('twitter', models.CharField(blank=True, max_length=200, verbose_name='Твиттер')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Почта')),
                ('photo', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображения')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.country', verbose_name='Страна')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.organization', verbose_name='Должность')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.sex')),
                ('sphere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.sphere', verbose_name='Сфера')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.structure', verbose_name='Отдел')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.type')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
            },
        ),
    ]
